### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by davidhhessler** [plus3it/AMIgen8#1]
You say under "Status" that this work won't begin until two conditions are met (see below).  

> Status
This project is currently a stub. No content, beyond this README will be found here until well after CentOS.Org has published an official/final CentOS 8 AMI (see CO8 Build-Status) and the Fedora project has made EPEL8 available (see EPEL 8 Support Status).

CentOS.Org has published an official image and EPEL 8 is out.   Is there a timeline on this?  SPEL is waiting on this project to start their support of EL8

**Comment by ferricoxide** [comment]
At the time this project's stub was initiated, there was a sponsorship for the work but the mentioned baseline conditions were not met. That sponsorship has been drastically reduced – with this project being almost wholly de-prioritized under that sponsorship-umbrella.

Currently, it's a matter of getting hours allocated under the existing sponsorship or finding new sponsorship to have billable-hours to perform the work.

**Comment by ferricoxide** [comment]
Quick update:

I just did a search both via their [MarketPlace page](https://aws.amazon.com/marketplace/seller-profile?id=16cb8b03-256e-4dde-8f34-1b0f377efe89), a CLI-based search using their owner-id (679593333241) and looked at their [AWS page](https://wiki.centos.org/Cloud/AWS): the only published images appear to be for CO6 and CO7.

Also: looking at [bugs.centos.org](https://bugs.centos.org/view.php?id=16614), it appears that the CentOS team is indicating that they're still a few weeks out from publishing their first one. If that BugId's status is correct, even if I had the sponsorship _today_, it appears I don't have a suitable bootstrap/starting-point image.

You stated in your issue-opening comment:

> CentOS.Org has published an official image and EPEL 8 is out. Is there a timeline on this? SPEL is waiting on this project to start their support of EL8

Could you point me to the official, CentOS.Org-published AMI you're referencing?

**Comment by ferricoxide** [comment]
Internal priorities have changed – can no longer wait for CentOS.Org to publish an official AMI to the MarketPlace.

**Comment by ferricoxide** [comment]
Initial automation-content pending PR #2
